//Task 1 && Task 2
/*let promise = new Promise((resolve, reject) => {
  const success = true;
  if (success) {
    console.log("In success if");
    setTimeout(() => {
      let result = "All work is done!";
      resolve(result);
    }, 2000);
  } else {
    let result = "Something went wrong";
    reject(result);
  }
});

promise
  .then((result) => {
    console.log("In then promise handling");
    console.log(result);
  })
  .catch((error) => {
    console.log(error);
  });
*/

